version: "3.7"
services:
  nacos:
    image: "nacos/nacos-server:latest"
    container_name: "nacos-standalone-mysql"
    volumes:
      - "./logs/:/home/nacos/logs"
      - "./init.d/custom.properties:/home/nacos/init.d/custom.properties"
    environment:
      - "PREFER_HOST_MODE=hostname"
      - "MODE=standalone"
      - "SPRING_DATASOURCE_PLATFORM=mysql"
      - "MYSQL_SERVICE_HOST=192.168.4.162"
      - "MYSQL_SERVICE_DB_NAME=nacos"
      - "MYSQL_SERVICE_PORT=3307"
      - "MYSQL_SERVICE_USER=root"
      - "MYSQL_SERVICE_PASSWORD=123456"
    ports:
      - "8848:8848"
      - "9555:9555"
    depends_on:
      - "mysql-nacos"
    restart: "on-failure"
  mysql-nacos:
    image: "mysql:5.7.27"
    container_name: "mysql-nacos"
    ports:
      - "3307:3306"
    volumes:
      - "E:/mysql/data:/var/lib/mysql"
      - "E:/mysql/conf.d:/etc/mysql/conf.d"
    environment:
      - "MYSQL_ROOT_PASSWORD=123456"
      - "MYSQL_DATABASE=nacos"
      - "MYSQL_ROOT_HOST=%"
    command: [
      "mysqld",
      "--innodb-buffer-pool-size=20M",
      "--character-set-server=utf8",
      "--collation-server=utf8_general_ci",
      "--default-time-zone=+8:00",
      "--lower-case-table-names=1"
    ]
  prometheus:
    container_name: "prometheus"
    image: "prom/prometheus:latest"
    volumes:
      - "./prometheus/prometheus-standalone.yaml:/etc/prometheus/prometheus.yml"
    ports:
      - "9000:9000"
    depends_on:
      - "nacos"
    restart: "on-failure"
  grafana:
    container_name: "grafana"
    image: "grafana/grafana:latest"
    ports:
      - "3000:3000"
    restart: "on-failure"

